### ISSUE TITLE
build ta-lib python package fail on Mac OSX, how to set TA_LIBRARY_PATH

### ISSUE THREAD

**Issue by mickeydonkey** [mrjbq7/ta-lib#109]
I try to install ta-lib Python package on Mac, after `brew install ta-lib`, I get ta-lib dependency installed in `/usr/local/Cellar`, this is the location where library is commonly installed via Homebrew. 
then I tried both `pip install ta-lib` and `python setup.py install`, they yield same error, as folows: 
```
building 'talib.common' extension
/usr/bin/clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/**/miniconda3/envs/zpl/include -arch x86_64 -I/Users/**/miniconda3/envs/zpl/lib/python3.4/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Users/**/miniconda3/envs/zpl/include/python3.4m -c talib/common.c -o build/temp.macosx-10.6-x86_64-3.4/talib/common.o
talib/common.c:242:10: fatal error: 'ta-lib/ta_defs.h' file not found
#include "ta-lib/ta_defs.h"
```
I dig into the setup.py, For *nix platform, there is a environment variable TA_LIBRARY_PATH,  my question is how to set it such that build process can locate the ta-lib library?

**Comment by mickeydonkey** [comment]
BTW, numpy pandas and cython is already installed.

**Comment by mickeydonkey** [comment]
after putting 
```
export TA_LIBRARY_PATH='/usr/local/Cellar/ta-lib/0.4.0/lib'
export TA_INCLUDE_PATH='/usr/local/Cellar/ta-lib/0.4.0/include'
```
 before `pip install ta-lib`it works for me, python package is installed. but I get another problem when I import talib in python:
```
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/**/miniconda3/envs/zpl/lib/python3.4/site-packages/talib/__init__.py", line 4, in <module>
    from . import common
ImportError: dlopen(/Users/**/miniconda3/envs/zpl/lib/python3.4/site-packages/talib/common.so, 2): Library not loaded: /usr/local/opt/ta-lib/lib/libta_lib.0.dylib
  Referenced from: /Users/**/miniconda3/envs/zpl/lib/python3.4/site-packages/talib/common.so
  Reason: image not found
```

**Comment by mickeydonkey** [comment]
FINALLY by placing a hardlink in `/usr/local/opt` directory: `hln /usr/local/Cellar/ta-lib/0.4.0 ta-lib` I can call `import talib` now. One may need to install hln via `brew install hardlink-osx` before create the hardlink.
to summarize my (possibly ugly) solution:
```
export TA_LIBRARY_PATH='/usr/local/Cellar/ta-lib/0.4.0/lib'
export TA_INCLUDE_PATH='/usr/local/Cellar/ta-lib/0.4.0/include'
cd /usr/local/opt
hln /usr/local/Cellar/ta-lib/0.4.0 ta-lib
pip install ta-lib
```
@mrjbq7 maybe you can make this installation process a little more beginner-friendly?

**Comment by mrjbq7** [comment]
Okay so I guess it's good you got it to work, but installing on the Mac **is** easy and beginner-friendly:

```
$ brew install ta-lib
$ pip install ta-lib
```

When you install with ``brew``, it leaves all the ``lib`` and ``include`` files in ``/usr/local/Celler/ta-lib`` and then typically symlinks them into ``/usr/local/lib`` and ``/usr/local/include``.  If those symlinks are made everything works fine. I can only assume you either disable that step or you have some non-standard configuration, but the easy way to fix that is:

```
$ brew link ta-lib
Linking /usr/local/Cellar/ta-lib/0.4.0... 7 symlinks created
```

Regarding your possible issue where you set ``TA_LIBRARY_PATH`` and ``TA_INCLUDE_PATH`` to the ``/usr/local/Cellar/ta-lib`` and then somehow the binary that is built looks for ``/usr/local/opt/ta-lib/lib/libta_lib.0.dylib``, well thats because ``/usr/local/opt/ta-lib`` is a symlink to ``/usr/local/Cellar/ta-lib`` and what that error is saying is that ``/usr/local/opt/ta-lib/lib/libta_lib.0.dylib`` can't be found, which is weird because a default installation has that (it's a symlink to ``/usr/local/Cellar/ta-lib/lib/libta_lib.0.0.0.dylib``.

Anyway, it should all work.  It should not require hardlinks.  You must have gummed up the works somewhere, but if you can figure out what broke and if I can assist in any way by adding documentation or working around some aspect of ``brew`` that I'm not familiar with, please let me know.

**Comment by mickeydonkey** [comment]
```
$ sudo brew link ta-lib
Password:
Error: Cowardly refusing to 'sudo brew link'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```
seems Homebrew can't create links in those directory, either with or without sudo. 
I tried to create a symlink of /usr/local/opt/ta-lib before using hardlink, but it also gives me some error, that's why I choose hardlink finally.

**Comment by mrjbq7** [comment]
You shouldn't have to ``sudo``.  The ``/usr/local/`` should be owned and at least writable by your user.  That (I think) is reported by ``brew doctor``.  In fact, ``sudo`` an ``brew`` don't mix because that's a security risk.

**Comment by mrjbq7** [comment]
I have been trying to reproduce your error with using``TA_INCLUDE_PATH`` and ``TA_LIBRARY_PATH`` and can't seem to get the same problem.  I get a different one where the binary is still linked against ``/usr/local/lib/libta_lib.0.dylib`` even though that path doesn't exist:

```
$ otool -L talib/common.so
talib/common.so:
	/usr/local/lib/libta_lib.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
``` 

I'm not quite sure why that is, unless the linker has some cached state -- maybe I can reboot and try a clean test case later to try and reproduce.

Regarding user owned ``/usr/local``, the developers of ``brew`` suggest[1] doing:

```
sudo chown -R `whoami` /usr/local
```

---

[1] https://apple.stackexchange.com/questions/1393/are-my-permissions-for-usr-local-correct#comment1417_1393

**Comment by mickeydonkey** [comment]
I followed your suggestions and change the owner of `/usr/local` to myself. now I can install ta-lib python package in documented way. and I checkec `/usr/local/opt`, as you said, a symlink is there. cool, thank you!
