### ISSUE TITLE
STOCHRSI values are not inline with other online tools for Trade Analysis.

### ISSUE THREAD

**Issue by avnkailash** [mrjbq7/ta-lib#170]
I am testing STOCHRSI indicator and observed that the value  are not inline with the online trading analysis tool provided by investing.com. Also, SAR values too differ. 

Is there any mistake from my side? I have ensured that I have provided the same set of parameter values for both the indicators in my code.

**Comment by mcardillo55** [comment]
I have the same issue. I think it's related to #149 where a moving average is not applied to fastk.

**Comment by nareddyt** [comment]
I was doing some reading on how RSI is calculated, and I came across the following text on [this website](http://cns.bu.edu/~gsc/CN710/fincast/Technical%20_indicators/Relative%20Strength%20Index%20(RSI).htm):

> Important Note: The more data points that are used to calculate the RSI, the more accurate the results. The smoothing factor is a continuous calculation that - in theory - takes into account all of the closing values in the data set. If you start an RSI calculation in the middle of an existing data set, your values will only approximate the true RSI value. SharpCharts uses at least 250 data points prior to the starting date of any chart (assuming that much data exists) when calculating its RSI values. To duplicate its RSI number, you'll need to use at least that much data also.

Maybe we've been calculating RSI / StochRSI incorrectly all along? It seems like we need to include a lot of previous data for the smoothing calculation, even if the `timeperiod` is tiny. @pieroliviermarquis from #149 only used the number of datapoints that matched the `timeperiod` variable, so maybe the smoothing calculation wasn't accurate because they did not include any previous data?

I don't fully understand how the RSI calculation works, so let me know if the link above make sense!

**Comment by Elyasnz** [comment]
if a Python implementation of STOCHRSI is needed this [comment](https://github.com/TA-Lib/ta-lib-python/issues/594#issuecomment-1560640283) is useful
