### ISSUE TITLE
What indicator can give me the graph?

### ISSUE THREAD

**Issue by JafferWilson** [mrjbq7/ta-lib#185]
I have a graph like the following for showing buying and selling. See the following graph:  
![uenpm](https://user-images.githubusercontent.com/13446197/36775859-b6c7c658-1c89-11e8-8bd4-2c4d98e53e33.png)
But I could not understand which indicator will show this graph? I am not even seeing the fractal indicator in your library. Kindly, help me. I am using Python library for implementing Ta-Lib.

**Comment by mrjbq7** [comment]
Well, this is difficult because:

1) I don't know what that graph is, what it's displaying, what indicator is generating buy/sell signals, etc.  So, I don't know what indicator will show this graph either.

2) I don't know what a "fractal indicator" is.  Please provide a link or documentation if you want me to comment on it.  But probably not included in the TA-Lib C library as far as I can see.

Is this a feature request?  Is it a bug?  Is it a help-me-with-homework or a job assignment?  I'm even willing to provide help in the latter cases but need more information.

**Comment by JafferWilson** [comment]
@mrjbq7 Sure  it is here, please check it out. If it is not included in the library then it is a feature request from my side.
See the fractal indicator from here: https://www.investopedia.com/articles/trading/06/fractals.asp
Also I guess this will help: https://learn.tradimo.com/technical-analysis-how-to-work-with-indicators/fractals-indicator
I hope this will help .....

**Comment by mrjbq7** [comment]
Assuming you get a good specification for all 7 or 8 types of fractal indicators, they should be very easy to code.  Example code for type 1 is only a handful of lines:

https://quant.stackexchange.com/questions/18634/fractals-indicator-bill-williams-r-quantstrat/18645

**Comment by JafferWilson** [comment]
@mrjbq7 So will you add that in the library of yours .. it will be great If I could use it through your code....

**Comment by mrjbq7** [comment]
I suppose, if I had a clean definition for the indicator, I could help you with the code.  But, this project is only intended to be a wrapper for the TA-Lib C library.  Any indicators you'd like to have added should be done upstream or in separate projects.

**Comment by JafferWilson** [comment]
@mrjbq7 Thank you for your replies.
