### ISSUE TITLE
Error on compiling the library

### ISSUE THREAD

**Issue by Kaggia** [mrjbq7/ta-lib#188]
Hello, I've recently tried to install the library. So I did, in order:
- Downloaded "ta-lib-0.4.0-msvc.zip", and unzipped on "C:\"
- Downloaded "ta-lib-master", and unzipped on "C:\"
- I run the command " python setup.py install", while I'm positioned in the folder "C:\ta-lib-master"

But ( A very big but ), I couldn't compile the library cause a receive the error:
" c:\ta-lib-master\talib\_ta_lib.c(243658) : fatal error C1002: compiler is out of heap space in pass 2 "

I tried a couple of times, and nothing happened.

I run a Python and Anaconda x86 version, tell me if you would know some more information. 

I attach a txt file where i dumped the command's output. I'm in your hands, please help me out!
[error_report.txt](https://github.com/mrjbq7/ta-lib/files/1796786/error_report.txt)

**Comment by mrjbq7** [comment]
That's a report I've gotten periodically, due to the 255,000 line C file that we compile it seems to need a lot of memory on certain compiler versions.  Not sure how much, or how easy it would be to reduce the memory needs.

On Windows, you have another option, which is pre-compiled binaries that are provided here:

https://www.lfd.uci.edu/~gohlke/pythonlibs/

It's also nice because they provide 64-bit versions too.

The main difference between ``ta-lib-master`` and the 0.4.16 version they have is that we added a lightweight wrapper of the functions that support ``pandas.Series`` as inputs.  Other than that, the last release was pretty solid I think.

**Comment by Kaggia** [comment]
I installed successfully the 0.4.16 version from a .whl file, so thanks!

**Comment by mrjbq7** [comment]
(Using ``master`` branch)
