### ISSUE TITLE
ATR Implementation Incorrect?

### ISSUE THREAD

**Issue by canigithub** [mrjbq7/ta-lib#271]
Based on the jar decompiled codes, in Core.java line 1772:

```
    prevATR *= optInTimePeriod - 1;
```

This line is supposed to calculate previous total value based on the previous average value, where the divisor is 'optInTimePeriod'. However, I think the correct implementation should be 

```
    prevATR *= optInTimePeriod;
```

i.e. optInTimePeriod shouldn't be subtracted by 1. 

Any one have any opinions?

**Comment by mrjbq7** [comment]
I'd have to look more in depth, but it looks like they multiply by ``period - 1``, add the new observation and then divide by ``period``.  That feels correct, but I didn't look in detail.

This isn't really the place for this question, though, since this is just the Python wrapper for the underlying C library.
