### ISSUE TITLE
 Question: How to add RMA indicator

### ISSUE THREAD

**Issue by haljishi** [mrjbq7/ta-lib#568]
How to add RMA indicator ? I don't see it bulit in in ta lib

https://www.tradingcode.net/tradingview/relative-moving-average/

**Comment by trufanov-nok** [comment]
TradingView's RMA is equal to TDA's Wilders() and equal to TA-Lib's EMA with 
`#define PER_TO_K( per ) ((double)1.0 / (double)(per))`
instead of
`#define PER_TO_K( per ) ((double)2.0 / ((double)(per + 1)))`

If you don't need EMA or any indicator that is based on EMA, you may edit this line in `ta-lib/c/src/ta_func/ta_utility.h` and rebuild the ta-lib. And EMA become RMA.

**Comment by haljishi** [comment]
thank you so much for your help
