### ISSUE TITLE
33 nan data type in the macd result.What does it mean?

### ISSUE THREAD

**Issue by no13bus** [mrjbq7/ta-lib#65]
I type these code in ipython:
```
import pandas.io.data as web    
import pandas as pd
import talib as ta
import matplotlib.pyplot as plt

# Download SP500 data with pandas
spy = web.get_data_yahoo('SPY', '2012-01-01')

macd1, macd2, macd3 = ta.MACD(spy.Close, 26, 12, 9)
```
Then I get `numpy.ndarray` data type. But I see there are 33 `nan` data type. So it just because of  `26`,`12`,`9` in the ta.MACD function. Yes, they stand for the fast EMA12, the slow EMA26, and EMA9.
But why there are 33 `nan` data? 
DO it mean that these 33 data is not useful for the MACD Indicator? And we can draw the DIFF, DEA line    and macd column without them?
https://github.com/mrjbq7/ta-lib/issues/new#

**Comment by Depwater** [comment]
I have same confused with you, and thanks to @mrjbq7 's answer, I have understood why there is 33 Nan data in result. And I also found out why there is a little difference between talib.macd's Diff and (talib.ema(12)-talib.ema(26)), because in talib.macd, in process of calculating diff, they need calculate ema12 first, but to make sure eam12 and ema26 come out at the same time, the first result of ema12 is set to the average of No.15 price data to No.26 price data, not the No.1 price data to No.12 price data. That's why difference happened.
